### ISSUE TITLE
Finalstretch delays before turning on after first time

### ISSUE THREAD

**Issue by PIXELATOR37** [v6cord/VVVVVV-CE#15]
The title kind of explains it; after finalstretch has been turned on and off, turning it back on any subsequent times in the play session will have no effect until after some certain time interval.
![2020-05-01_17-30-44](https://user-images.githubusercontent.com/45022852/80843148-8a1fff80-8bd1-11ea-818d-a77539a9ed29.gif)

**Comment by leo60228** [comment]
what
