### ISSUE TITLE
Game crashes when in room with 1x1 disappearing platforms during death

### ISSUE THREAD

**Issue by xnossisx** [v6cord/VVVVVV-CE#16]
![ezgif com-optimize](https://user-images.githubusercontent.com/36285517/81515144-3495d200-92f8-11ea-8ee5-5814ad50b489.gif)

I was recently testing my level in VVVVVV-CE, which contains quite a few of these red 1x1 disappearing platforms. However, when I was in the room, no matter what, if I died, a few frames beforehand, the game would crash. This happened to me multiple times, as well. However, when I tried this with the original game, the behavior went away, as well as when I went into the editor. In fact, after doing this (and also accidentally adding an enemy bounds box), everything seemed normal, for some inexplicable reason.

**Comment by InfoTeddy** [comment]
I'll need some more comprehensive repro steps. If I take your title literally (dying at all in a room with 1x1 disappearing platforms results in a crash) and make a test level myself, I don't get the crash.

Also, what version of VCE are you using?

> However, when I was in the room, no matter what, if I died, a few frames beforehand, the game would crash.

"a few frames beforehand" A few frames before what, exactly?

> However, when I tried this with the original game, the behavior went away, as well as when I went into the editor. In fact, after doing this ([...]), everything seemed normal, for some inexplicable reason.

So after trying to do this crash in vanilla, it didn't happen, and then when you went back to VCE after that, it also didn't happen?

**Comment by xnossisx** [comment]
First, the version is 1.0pre-1.
Second, the crash appeared to occur a few frames before I was supposed to die,
and third, yes.
I'm beginning to suspect the problem occurred when I didn't have the level exactly in the VCE format, as it seems that once I started tinkering with the level in the VCE editor, it might have somehow changed in a way that fixed it. Perhaps another step in the reproduction of this glitch would be to create a level in the original version of VVVVVV, and then try to play it in VCE. I don't particularly know the exact cause of the issue, and the condition for this happening might be so esoteric I'll never determine it.

**Comment by InfoTeddy** [comment]
This sounds like the bug that 530105368065fc66cb51137295e318d37771ff74 fixes, that being 1x1 disappearing platforms will cause an infinite loop if the level isn't a VCE level. For reference, a level is a VCE level if it has a greater than zero `vceversion` attribute in the `<MapData>` tag. Currently `vceversion` should be 1, so the top of the level XML should look like:

```xml
<?xml version="1.0" ?>
<MapData version="2" vceversion="1">
```

If you save a level in the VCE editor, it will have this attribute. If you save a level in the vanilla editor, it will *not* have this attribute. Also, a vanilla level being playtested in VCE is still treated as a VCE level, and the only way to play a vanilla level with vanilla compatibility mode inside VCE is to play it normally.

I'm guessing your "tinkering with the level" included saving the level with VCE's editor.

Back to the above, 530105368065fc66cb51137295e318d37771ff74 isn't in a released version of VCE yet (it was committed on April 1st while 1.0-pre1 was released on March 26th). So could you try a CI build of VCE and tell me if the vanilla level (not the vanilla-level-but-saved-in-VCE, and not the vanilla-level-but-using-in-editor-playtesting-in-VCE, just the original level in VCE) still has an infinite loop with the 1x1 disappearing platforms?

You can grab the latest build (at the time of writing) from [here](/v6cord/VVVVVV-CE/runs/661804205). I don't know what operating system you're on so I won't give you a more direct link. Just click "Artifacts" in the upper-right corner and select your OS accordingly.

**Comment by xnossisx** [comment]
When I tried to reproduce the glitch in the latest version of VCE, the glitch did not occur (on my OS, Windows 10). It appears this bug has been fixed. Thank you!
