### ISSUE TITLE
changeplayercolour() does not persist upon death

### ISSUE THREAD

**Issue by DoubleDenial** [v6cord/VVVVVV-CE#17]
I think the player color resetting every time you die negates a lot of the usefulness of changing the player color in the first place. Could this be changed?

**Comment by InfoTeddy** [comment]
This is a vanilla quirk, but it has been requested before to be fixed. The main reason the player color is reset upon respawn is because their color is changed to the death color when they're dying.

**Comment by AllyTally** [comment]
No.
`changeplayercolour()` resetting to cyan upon death is vanilla behavior that has no reason to be changed, as there are already workarounds.
This is not a bug.

In VCE, the easiest way would be using a callback.

In a script that Viridian touches, add this: `setcallback(on_death_end,change_color)`
And then make a script called `change_color` with this line: `changeplayercolour(<color here>)`
The script `change_color` is ran every time the player respawns, so setting their color during that should work.

**Comment by leo60228** [comment]
No.
Internal scripting commands not working in custom levels is vanilla behavior that has no reason to be changed, as there are already workarounds. This is not a bug.

**Comment by AllyTally** [comment]
Leo, the command works perfectly fine and as intended. If you want to say otherwise, go make a PR to upstream or something.

**Comment by InfoTeddy** [comment]
I'm confused - the tone of his message seems to be in favor of keeping this issue *closed*, yet he re-opened it for some reason?

**Comment by AllyTally** [comment]
His message was making fun of mine, see the "Internal scripting commands not working in custom levels is vanilla behavior" part.

The issue didn't need to be reopened though.

**Comment by leo60228** [comment]
There's no reason not to change this. Every single level I've seen using these commands has had to work around this behavior.
