### ISSUE TITLE
Don't know how to run

### ISSUE THREAD

**Issue by R3Ked** [v6cord/VVVVVV-CE#6]
How do I play this? There isn't a .exe anywhere!

**Comment by InfoTeddy** [comment]
Please see https://github.com/v6cord/VVVVVV-CE/releases

Note that this is intended to be used to play custom levels, so you'll need to download a custom level that runs on VCE, too. VCE isn't a standalone game or anything.

**Comment by R3Ked** [comment]
Ok, but what file do I run to play a level?

**Comment by InfoTeddy** [comment]
You don't run any specific file to play a level, that's not how it works. To play a level, you have to put its `.vvvvvv` file (or `.zip`) into your `levels` folder, which on Windows would be `Documents\VVVVVV\levels`. Then you open VCE, select "play levels", select "play a level", then navigate to the level and select it.

**Comment by leo60228** [comment]
What? The releases page has installation instructions for all platforms. The only .exe file in the Windows distribution is VVVVVV-CE.exe.

**Comment by R3Ked** [comment]
I don't have a vvvvvv-ce.exe.

**Comment by InfoTeddy** [comment]
Please refer to my [previous comment](#issuecomment-609499983):

> Please see https://github.com/v6cord/VVVVVV-CE/releases

**Comment by R3Ked** [comment]
Oops, I didn't extract it

**Comment by R3Ked** [comment]
Still don't have a VVVVVV-CE.exe. Closest I have is a .desktop file of the same name, but renaming that won't work.

**Comment by InfoTeddy** [comment]
Did you download the wrong one? It sounds like you downloaded the one for Linux or something.

**Comment by R3Ked** [comment]
I pushed Clone / Download > Download Zip. I'm not sure how that could've went wrong.

**Comment by InfoTeddy** [comment]
Please refer to my [previous comment](#issuecomment-609503947):

> Please refer to my [previous comment](#issuecomment-609499983):
> 
> > Please see https://github.com/v6cord/VVVVVV-CE/releases

What you've downloaded is the repository, and *not* a release of VCE. If you click on the link above, you can download a `.zip` file containing `VVVVVV-CE.exe`.

**Comment by R3Ked** [comment]
Ok, I fixed it. Turns out that I just downloaded the wrong thing.
