### ISSUE TITLE
Add in box enemies

### ISSUE THREAD

**Issue by R3Ked** [v6cord/VVVVVV-CE#9]
There are unused enemies that look like boxes, shown here:
![box](https://user-images.githubusercontent.com/20342336/78621326-353dd300-7837-11ea-8e09-8c0b5bc59688.png)
These should be added because the existing square enemies might not be enough for some people.

**Comment by InfoTeddy** [comment]
> There are unused enemies that look like boxes, shown here:

These are simply the textures used if you have an invalid enemy type when `createentity`ing entity 1.

> These should be added because the existing square enemies might not be enough for some people.

A better way would be to simply allow people to use whatever enemy sprite and animation type they want. Luckily, you can already do that with `setentitydata()`.

**Comment by leo60228** [comment]
@InfoTeddy This is a reasonable feature request. By that logic, we shouldn't have changed anything in the editor because you could use `setentitydata` instead.
